# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bsadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAnalisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Especie')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Establecimiento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Motivos')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Veterinario')),
            ],
        ),
    ]
