# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0002_parametros_grupo'),
        ('bsuser', '0002_auto_20161119_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividuoPadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30, verbose_name='Identificacion / N° de Caravana')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Raza')),
            ],
        ),
        migrations.RemoveField(
            model_name='individuos',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='individuos',
            name='raza',
        ),
        migrations.AlterField(
            model_name='individuos',
            name='categoriae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bsadmin.CategoriaE'),
        ),
        migrations.AddField(
            model_name='individuos',
            name='padre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bsuser.IndividuoPadre'),
            preserve_default=False,
        ),
    ]
