# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresreferencia',
            name='valorDef',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='valoresreferencia',
            name='valorRef',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
