# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='visualizacion',
            new_name='visualizacion1',
        ),
    ]
