# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0002_parametros_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivos',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
