# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0003_auto_20170928_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(default='momoj', max_length=50),
            preserve_default=False,
        ),
    ]
