# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0003_auto_20170302_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raza',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
