# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0004_empresa_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default='rrr', upload_to='img'),
            preserve_default=False,
        ),
    ]
