# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0005_auto_20170425_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
