# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercerizacion',
            name='detalle',
            field=models.TextField(default='eee', verbose_name='Detalle'),
            preserve_default=False,
        ),
    ]
