# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminacionprotocolo',
            name='usuario',
            field=models.CharField(default='', max_length=30, verbose_name='Responsable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleanalisis',
            name='valor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eliminacionprotocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.Protocolo'),
        ),
    ]
