# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleanalisis',
            name='padre',
        ),
        migrations.AddField(
            model_name='detalleanalisis',
            name='solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bsuser.SolicitudAnalisis'),
            preserve_default=False,
        ),
    ]
