# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0002_auto_20171029_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleanalisis',
            name='valor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Confirmado'),
        ),
    ]
