# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0002_auto_20170831_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleanalisis',
            name='individuo',
        ),
        migrations.AddField(
            model_name='detalleanalisis',
            name='individuoPadre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bsuser.IndividuoPadre'),
            preserve_default=False,
        ),
    ]
