# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0003_auto_20170902_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tercerizar',
            new_name='Tercerizacion',
        ),
    ]
