# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0003_auto_20171124_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercerizacion',
            name='institucion',
            field=models.CharField(max_length=50),
        ),
    ]
