# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0004_auto_20171007_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminacionprotocolo',
            name='usuario',
            field=models.CharField(default='', max_length=30, verbose_name='Responsable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleanalisis',
            name='valor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
