# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bsadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleAnalisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAnalisisPadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionProtocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivoBaja', models.TextField(verbose_name='Motivo de Baja')),
            ],
        ),
        migrations.CreateModel(
            name='IndividuoPadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=30, verbose_name='Identificacion / N° de Caravana')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Raza')),
            ],
        ),
        migrations.CreateModel(
            name='Individuos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nombre')),
                ('edad', models.CharField(blank=True, max_length=2, null=True, verbose_name='Edad')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra'), ('X', 'NS/NC')], default='X', max_length=1, null=True, verbose_name='Sexo')),
                ('libretasanitaria', models.CharField(blank=True, max_length=15, null=True)),
                ('categoriae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bsadmin.CategoriaE')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.IndividuoPadre')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Numero de Protocolo')),
                ('activo', models.BooleanField(default=False, verbose_name='Estado Confirmado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAnalisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Especie')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Establecimiento')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Motivos')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Tercerizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de Envío')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('institucion', models.CharField(max_length=20)),
                ('detalleanalisispadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.DetalleAnalisisPadre')),
            ],
        ),
        migrations.AddField(
            model_name='eliminacionprotocolo',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bsuser.Protocolo'),
        ),
        migrations.AddField(
            model_name='detalleanalisispadre',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.Protocolo'),
        ),
        migrations.AddField(
            model_name='detalleanalisispadre',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.SolicitudAnalisis'),
        ),
        migrations.AddField(
            model_name='detalleanalisis',
            name='individuoPadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.IndividuoPadre'),
        ),
        migrations.AddField(
            model_name='detalleanalisis',
            name='parametros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Parametros'),
        ),
        migrations.AddField(
            model_name='detalleanalisis',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.SolicitudAnalisis'),
        ),
    ]
