# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0002_tercerizacion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminacionprotocolo',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsuser.Protocolo'),
        ),
    ]
