# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0004_auto_20171007_2126'),
        ('bsuser', '0005_auto_20171028_2057'),
    ]

    operations = [
    ]
