# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0005_eliminacionprotocolo_usuario'),
        ('bsuser', '0006_merge_20171031_1151'),
    ]

    operations = [
    ]
