# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsuser', '0007_merge_20171108_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleanalisis',
            name='valor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
