# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-28 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0002_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='valoresreferencia',
            name='activo',
        ),
    ]
