# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0003_auto_20171028_2057'),
        ('bsadmin', '0003_auto_20171028_0016'),
    ]

    operations = [
    ]
