# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='grupo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
