# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0004_auto_20170302_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriae',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='especializacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='explotacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motivos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametros',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='raza',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='valoresreferencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='categoriae',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='especializacion',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Especializacion'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='explotacion',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Explotacion'),
        ),
        migrations.AlterField(
            model_name='motivos',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Motivos'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True, verbose_name='Muestra'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
