# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsadmin', '0006_auto_20170502_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametros',
            name='activo',
        ),
        migrations.AddField(
            model_name='parametros',
            name='diagnostico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bsadmin.Diagnostico'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='valoresreferencia',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='valoresreferencia',
            name='diagnostico',
        ),
        migrations.AlterUniqueTogether(
            name='valoresreferencia',
            unique_together=set([('especie', 'parametros')]),
        ),
    ]
